# 站点配置
site_name: '我的博客'
site_description: '分享技术与生活'
site_url: 'http://localhost:8000'
author: '博主'
language: 'zh-CN'

# 主题设置
theme: 'default'

# 分页设置
posts_per_page: 10

# 日期格式
date_format: '%Y-%m-%d'

# Markdown 扩展
markdown_extensions:
  - fenced_code
  - codehilite
  - tables
  - toc
  - footnotes 